const resumeData = {
  en: {
    eyebrow: "Product Executive",
    name: "Daniel Vásquez",
    role: "Product · Software · Finance",
    disciplines: "Global product leadership across startups, agencies, and Fortune 100 organizations",
    email: "danielvp1987@gmail.com",
    location: "Mexico City · Aberdeen, UK",
    links: {
      website: { url: "https://goldenfrijoles.com", label: "goldenfrijoles.com" },
      linkedin: { url: "https://www.linkedin.com/in/danielvasquezparedes" },
      goldenfrijoles: { url: "https://goldenfrijoles.com", label: "goldenfrijoles.com" },
      github: { url: "https://github.com/danybgoode", label: "GitHub" },
    },
    stats: [
      { figure: "15+", label: "Years in product leadership" },
      { figure: "$70M+", label: "Budget owned, AB InBev" },
      { figure: "70+", label: "People led, cross-functional" },
      { figure: "4", label: "Ventures founded" },
      { figure: "MSc", label: "Finance, Univ. of Aberdeen" },
      { figure: "MX / UK", label: "Mexico City & Aberdeen" },
    ],
    snapshot: [
      "Product executive building software, marketplaces, and AI-enabled organizations across fifteen years of global leadership.",
      "Experience spans zero-to-one startups, high-stakes M&A integrations, and Fortune 100 scale — most recently directing a seventy-person team and a $70M+ portfolio at AB InBev.",
      "Focused on turning ambiguity into systems that scale, bridging technical architecture, financial strategy, and organizational design.",
      "Outside corporate roles, I design the operating systems product teams use to build with AI agents — dobby-foundation, my own plugin-based framework, turns planning, QA, and reporting into agent-run routines with human approval gates.",
    ],
    experience: {
      featured: [
        {
          company: "miyagisanchez.com / goldenfrijoles.com",
          dates: "2025 — Present",
          title: "Founder · Local marketplace & agentic Product Management platform",
          chain: [
            "Designed dobby-foundation — a portable operating system for AI-agent product work",
            "Automated the full delivery loop: planning, QA gates, PR review, PMO reporting",
            "Multi-agent orchestration across Claude Code and Cowork, with human-approval gates by design",
          ],
          tags: "Open-sourced as a reusable plugin marketplace · CI-enforced portability guards · reproducible skill packaging",
        },
        {
          company: "AB InBev",
          dates: "2020 — 2023",
          title: "Global Principal Product Manager · Largest brewer worldwide",
          chain: ["Built global rewards ecosystem", "70+ person product & engineering team", "$70M+ portfolio"],
          tags: "Central America · Europe · South Korea — campaigns activated at the Super Bowl and The Voice Brasil",
        },
        {
          company: "Linio Group",
          dates: "2019 — 2020",
          title: "Senior Product Manager · Mexico City",
          chain: ["Falabella acquisition", "Directed post-M&A systems integration", "Unified multi-platform infrastructure"],
        },
        {
          company: "Bicimensajero.com",
          dates: "2014 — 2016",
          title: "Founder · On-demand bike logistics, pre-AI landscape",
          chain: ["Built the stack solo", "Scaled to 100+ messengers", "Negotiated acquisition exit"],
        },
        {
          company: "CTIN",
          dates: "2012 — 2014",
          title: "Team Lead · Centro de Tecnología e Innovación",
          chain: ["Bitcoin remittance platform", "5,000+ active users", "América Móvil / Grupo Carso proposal"],
          tags: "Second team: gamified coding-literacy comic platform for children",
        },
      ],
      earlier: [
        { company: "Wagento Commerce", title: "Head of Customer Experience & Project Management", dates: "2017 — 2019" },
        { company: "MagmaLabs", title: "Product Manager", dates: "2016 — 2017" },
        { company: "Pokapok.mx", title: "Founder — corporate wellness platform", dates: "2016 — 2017" },
        { company: "Nuuch Tech", title: "Founder & Principal Consultant — Magento, CRM, agile coaching", dates: "2012 — 2015" },
        { company: "Blue Label Telecoms", title: "Business Analyst", dates: "2010 — 2011" },
        { company: "CompuCom · Accenture", title: "Tech Support · Customer Service", dates: "2006 — 2010" },
      ],
    },
    skills: [
      "Leadership",
      "Product Strategy",
      "Organization Design",
      "Platform Thinking",
      "Marketplace Design",
      "Multi-Agent Orchestration",
      "Financial Modeling",
      "System Architecture",
      "M&A Integration",
      "Agile Coaching",
      "E-commerce (Magento)",
      "DevOps",
    ],
    timeline: [
      { year: "2025", role: "Founder, miyagisanchez.com and goldenfrijoles.com", sub: "Local marketplace & Agentic Product Management Platform", current: true },
      { year: "2023", role: "MSc Finance", sub: "University of Aberdeen" },
      { year: "2020", role: "AB InBev", sub: "Global Group → Principal Product Manager" },
      { year: "2019", role: "Linio Group", sub: "Senior Product Manager" },
      { year: "2016", role: "MagmaLabs", sub: "Product Manager" },
      { year: "2014", role: "Founder, Bicimensajero", sub: "On-demand logistics" },
      { year: "2012", role: "CTIN", sub: "Team Lead" },
    ],
    philosophy: "I build products on purpose.",
    tldr: {
      greeting: "Hi, I'm Daniel Vásquez",
      intro: "Some things about me:",
      bullets: [
        "Learned to code in high school while managing a local computer shop",
        "Started as tech support, then software development to later settle in Product Management",
        "Everything I build now runs through agents, from planning to shipping",
        "Built <a href=\"https://github.com/danybgoode/dobby-foundation\" target=\"_blank\" rel=\"noopener noreferrer\">dobby-foundation</a>, my own open-sourced operating system for AI-agent product work — plugins for planning, QA, and reporting, reused across every project I build",
        "Currently building <a href=\"https://goldenfrijoles.com\" target=\"_blank\" rel=\"noopener noreferrer\">goldenfrijoles.com</a>, my idea of how to do Product Management with agents",
      ],
      punchline: "Have a knack for taking things from 0 to the whole world.",
      contactText: "Find me at:",
      contactEmail: "danielvp1987@gmail.com",
    },
    ui: {
      pageTitle: "Daniel Vásquez — Product Executive",
      metaDesc: "Product executive building software, marketplaces, and AI-enabled organizations across 15 years of global leadership.",
      snapshotTitle: "Executive Snapshot",
      experienceTitle: "Selected Experience",
      earlierTitle: "Earlier Career",
      capabilitiesTitle: "Capabilities",
      timelineTitle: "Timeline",
      approachTitle: "Approach",
      tldrButton: "TL;DR",
      classicButton: "Classic",
      lastUpdated: "Last updated September 2026",
      viewMarkdown: "View Markdown",
      markdownUrl: "/resume.md",
      downloadPdf: "PDF",
      emailLabel: "Email",
      linkedinLabel: "LinkedIn",
      websiteLabel: "Website",
      statsTitle: "At a Glance",
      pdfFooterNote: "Extended profile, full timeline & capabilities at",
      pdfPrintButton: "Print / Save as PDF",
      pdfBackLink: "← Back to site",
    },
  },
  es: {
    eyebrow: "Ejecutivo de Producto",
    name: "Daniel Vásquez",
    role: "Producto · Software · Finanzas",
    disciplines: "Liderazgo global de producto en startups, agencias y empresas Fortune 100",
    email: "danielvp1987@gmail.com",
    location: "Ciudad de México · Aberdeen, UK",
    links: {
      website: { url: "https://goldenfrijoles.com", label: "goldenfrijoles.com" },
      linkedin: { url: "https://www.linkedin.com/in/danielvasquezparedes" },
      goldenfrijoles: { url: "https://goldenfrijoles.com", label: "goldenfrijoles.com" },
      github: { url: "https://github.com/danybgoode", label: "GitHub" },
    },
    stats: [
      { figure: "15+", label: "Años en liderazgo de producto" },
      { figure: "$70M+", label: "Presupuesto gestionado, AB InBev" },
      { figure: "70+", label: "Personas lideradas, equipos multidisciplinarios" },
      { figure: "4", label: "Emprendimientos fundados" },
      { figure: "MSc", label: "Finanzas, Univ. of Aberdeen" },
      { figure: "CDMX / UK", label: "Ciudad de México y Aberdeen" },
    ],
    snapshot: [
      "Ejecutivo de producto creando software, marketplaces y organizaciones impulsadas por IA a lo largo de quince años de liderazgo global.",
      "Trayectoria que abarca startups desde cero, integraciones estratégicas de M&A y escala Fortune 100 — recientemente dirigiendo un equipo de 70 personas y un portafolio de más de $70M USD en AB InBev.",
      "Enfocado en transformar la ambigüedad en sistemas escalables, articulando arquitectura técnica, estrategia financiera y diseño organizacional.",
      "Fuera de roles corporativos, diseño los sistemas operativos que los equipos de producto usan para construir con agentes de IA — dobby-foundation, mi propio framework basado en plugins, convierte la planeación, el QA y el reporteo en rutinas ejecutadas por agentes con puntos de aprobación humana.",
    ],
    experience: {
      featured: [
        {
          company: "miyagisanchez.com / goldenfrijoles.com",
          dates: "2025 — Presente",
          title: "Fundador · Marketplace local y plataforma de Product Management con agentes",
          chain: [
            "Diseño de dobby-foundation — un sistema operativo portátil para trabajo de producto con agentes de IA",
            "Automatización del ciclo completo de entrega: planeación, gates de QA, revisión de PRs, reporteo tipo PMO",
            "Orquestación multi-agente entre Claude Code y Cowork, con puntos de aprobación humana por diseño",
          ],
          tags: "Código abierto como marketplace de plugins reutilizable · guardas de portabilidad exigidas por CI · empaquetado reproducible de skills",
        },
        {
          company: "AB InBev",
          dates: "2020 — 2023",
          title: "Global Principal Product Manager · La cervecera más grande del mundo",
          chain: ["Creación del ecosistema global de recompensas", "Equipo de 70+ personas de producto e ingeniería", "Portafolio de +$70M USD"],
          tags: "Centroamérica · Europa · Corea del Sur — campañas activadas en el Super Bowl y The Voice Brasil",
        },
        {
          company: "Linio Group",
          dates: "2019 — 2020",
          title: "Senior Product Manager · Ciudad de México",
          chain: ["Adquisición por Falabella", "Liderazgo de integración de sistemas post-M&A", "Infraestructura multiplataforma unificada"],
        },
        {
          company: "Bicimensajero.com",
          dates: "2014 — 2016",
          title: "Fundador · Logística bajo demanda en bicicleta, era pre-IA",
          chain: ["Desarrollo completo del stack tecnológico", "Escalamiento a más de 100 mensajeros", "Negociación de salida por adquisición"],
        },
        {
          company: "CTIN",
          dates: "2012 — 2014",
          title: "Líder de Equipo · Centro de Tecnología e Innovación",
          chain: ["Plataforma de remesas con Bitcoin", "5,000+ usuarios activos", "Propuesta para América Móvil / Grupo Carso"],
          tags: "Segundo equipo: cómic interactivo y gamificado para enseñar programación a niños",
        },
      ],
      earlier: [
        { company: "Wagento Commerce", title: "Director de Experiencia de Cliente y Gestión de Proyectos", dates: "2017 — 2019" },
        { company: "MagmaLabs", title: "Product Manager", dates: "2016 — 2017" },
        { company: "Pokapok.mx", title: "Fundador — plataforma de bienestar corporativo", dates: "2016 — 2017" },
        { company: "Nuuch Tech", title: "Fundador y Consultor Principal — Magento, CRM, coaching ágil", dates: "2012 — 2015" },
        { company: "Blue Label Telecoms", title: "Analista de Negocio", dates: "2010 — 2011" },
        { company: "CompuCom · Accenture", title: "Soporte Técnico y Servicio al Cliente", dates: "2006 — 2010" },
      ],
    },
    skills: [
      "Liderazgo",
      "Estrategia de Producto",
      "Diseño Organizacional",
      "Pensamiento de Plataforma",
      "Diseño de Marketplaces",
      "Orquestación Multi-Agente",
      "Modelado Financiero",
      "Arquitectura de Sistemas",
      "Integración M&A",
      "Coaching Ágil",
      "Comercio Electrónico (Magento)",
      "DevOps",
    ],
    timeline: [
      { year: "2025", role: "Fundador, miyagisanchez.com y goldenfrijoles.com", sub: "Marketplace local y plataforma de Product Management con agentes", current: true },
      { year: "2023", role: "MSc en Finanzas", sub: "Universidad de Aberdeen" },
      { year: "2020", role: "AB InBev", sub: "Global Group → Principal Product Manager" },
      { year: "2019", role: "Linio Group", sub: "Senior Product Manager" },
      { year: "2016", role: "MagmaLabs", sub: "Product Manager" },
      { year: "2014", role: "Fundador, Bicimensajero", sub: "Logística bajo demanda" },
      { year: "2012", role: "CTIN", sub: "Líder de Equipo" },
    ],
    philosophy: "Construyo productos con propósito.",
    tldr: {
      greeting: "Hola, soy Daniel Vásquez",
      intro: "Algunas cosas sobre mí:",
      bullets: [
        "Aprendí a programar en la prepa mientras administraba una tienda local de computación",
        "Empecé en soporte técnico, pasé a desarrollo de software y después me consolidé en Product Management",
        "Todo lo que construyo ahora pasa por agentes, desde la planeación hasta el lanzamiento",
        "Construí <a href=\"https://github.com/danybgoode/dobby-foundation\" target=\"_blank\" rel=\"noopener noreferrer\">dobby-foundation</a>, mi propio sistema operativo de código abierto para trabajo de producto con agentes de IA — plugins para planeación, QA y reporteo, reutilizados en cada proyecto que construyo",
        "Actualmente construyendo <a href=\"https://goldenfrijoles.com\" target=\"_blank\" rel=\"noopener noreferrer\">goldenfrijoles.com</a>, mi idea de cómo hacer Product Management con agentes",
      ],
      punchline: "Tengo facilidad para llevar las cosas de 0 a todo el mundo.",
      contactText: "Encuéntrame en:",
      contactEmail: "danielvp1987@gmail.com",
    },
    ui: {
      pageTitle: "Daniel Vásquez — Ejecutivo de Producto",
      metaDesc: "Ejecutivo de producto creando software, marketplaces y organizaciones impulsadas por IA a lo largo de 15 años de liderazgo global.",
      snapshotTitle: "Resumen Ejecutivo",
      experienceTitle: "Experiencia Destacada",
      earlierTitle: "Trayectoria Previa",
      capabilitiesTitle: "Capacidades",
      timelineTitle: "Trayectoria",
      approachTitle: "Enfoque",
      tldrButton: "TL;DR",
      classicButton: "Clásico",
      lastUpdated: "Última actualización: Septiembre 2026",
      viewMarkdown: "Ver Markdown",
      markdownUrl: "/resume-es.md",
      downloadPdf: "PDF",
      emailLabel: "Correo",
      linkedinLabel: "LinkedIn",
      websiteLabel: "Sitio Web",
      statsTitle: "En Cifras",
      pdfFooterNote: "Perfil extendido, trayectoria completa y capacidades en",
      pdfPrintButton: "Imprimir / Guardar como PDF",
      pdfBackLink: "← Volver al sitio",
    },
  },
};

// Default export has both en and es, and aliases top-level to en for backward-compatibility in templates
export default {
  ...resumeData.en,
  en: resumeData.en,
  es: resumeData.es,
};