export default {
  eyebrow: "Product Executive",
  name: "Daniel Vásquez",
  role: "Software · Product · Finance",
  disciplines: "Global product leadership across startups, agencies, and Fortune 100 organizations",
  email: "danielvp1987@gmail.com",
  location: "Aberdeen, Scotland",
  links: {
    website: { url: "https://miyagisanchez.com", label: "miyagisanchez.com" },
    linkedin: { url: "https://www.linkedin.com/in/danielvasquezparedes" },
  },
  stats: [
    { figure: "15+", label: "Years in product leadership" },
    { figure: "$70M+", label: "Budget owned, AB InBev" },
    { figure: "70+", label: "People led, cross-functional" },
    { figure: "4", label: "Ventures founded" },
    { figure: "MSc", label: "Finance, Univ. of Aberdeen" },
    { figure: "MX / UK", label: "Mexico City & Aberdeen" },
  ],
  snapshot: [
    "Product executive building software, marketplaces, and AI-enabled organizations across fifteen years of global leadership.",
    "Experience spans zero-to-one startups, high-stakes M&A integrations, and Fortune 100 scale — most recently directing a seventy-person team and a $70M+ portfolio at AB InBev.",
    "Focused on turning ambiguity into systems that scale, bridging technical architecture, financial strategy, and organizational design.",
  ],
  experience: {
    featured: [
      {
        company: "AB InBev",
        dates: "2020 — 2023",
        title: "Global Principal Product Manager · Largest brewer worldwide",
        chain: ["Built global rewards ecosystem", "70+ person product & engineering team", "$70M+ portfolio"],
        tags: "Central America · Europe · South Korea — campaigns activated at the Super Bowl and The Voice Brasil",
      },
      {
        company: "Linio Group",
        dates: "2019 — 2020",
        title: "Senior Product Manager · Mexico City",
        chain: ["Falabella acquisition", "Directed post-M&A systems integration", "Unified multi-platform infrastructure"],
      },
      {
        company: "Bicimensajero.com",
        dates: "2014 — 2016",
        title: "Founder · On-demand bike logistics, pre-AI landscape",
        chain: ["Built the stack solo", "Scaled to 100+ messengers", "Negotiated acquisition exit"],
      },
      {
        company: "CTIN",
        dates: "2012 — 2014",
        title: "Team Lead · Centro de Tecnología e Innovación",
        chain: ["Bitcoin remittance platform", "5,000+ active users", "América Móvil / Grupo Carso proposal"],
        tags: "Second team: gamified coding-literacy comic platform for children",
      },
    ],
    earlier: [
      { company: "Wagento Commerce", title: "Head of Customer Experience & Project Management", dates: "2017 — 2019" },
      { company: "MagmaLabs", title: "Product Manager", dates: "2016 — 2017" },
      { company: "Pokapok.mx", title: "Founder — corporate wellness platform", dates: "2016 — 2017" },
      { company: "Independent Consultancy", title: "Founder & Principal Consultant — Magento, CRM, agile coaching", dates: "2012 — 2015" },
      { company: "Blue Label Telecoms", title: "Business Analyst", dates: "2010 — 2011" },
      { company: "CompuCom · Accenture", title: "Tech Support · Customer Service", dates: "2006 — 2010" },
    ],
  },
  skills: [
    "Leadership",
    "Product Strategy",
    "Organization Design",
    "Platform Thinking",
    "Marketplace Design",
    "AI Workflows",
    "Financial Modeling",
    "System Architecture",
    "M&A Integration",
    "Agile Coaching",
    "E-commerce (Magento)",
    "DevOps",
  ],
  timeline: [
    { year: "2026", role: "Founder, Miyagi Sánchez", sub: "current — placeholder, confirm dates", current: true },
    { year: "2024", role: "MSc Finance", sub: "University of Aberdeen" },
    { year: "2020", role: "AB InBev", sub: "Global Group → Principal Product Manager" },
    { year: "2019", role: "Linio Group", sub: "Senior Product Manager" },
    { year: "2016", role: "MagmaLabs", sub: "Product Manager" },
    { year: "2014", role: "Founder, Bicimensajero", sub: "On-demand logistics" },
    { year: "2012", role: "CTIN", sub: "Team Lead" },
  ],
  philosophy: "I build products by combining business strategy, technical architecture, and organizational design. Execution matters, but judgment determines what's worth building in the first place — the hardest part of any product isn't the code, it's deciding what deserves to exist.",
};
