const resumeData = {
  en: {
    eyebrow: "Product Leadership · Agentic Delivery",
    name: "Daniel Vásquez",
    role: "Product Engineering · Agentic Delivery Systems",
    disciplines:
      "Fifteen years of product leadership from zero-to-one to Fortune 100 scale — now shipping production software with multi-agent teams, and building the operating system they run on.",
    email: "danielvp1987@gmail.com",
    location: "Mexico City · Aberdeen, UK",
    links: {
      website: { url: "https://miyagisanchez.com", label: "miyagisanchez.com" },
      linkedin: { url: "https://www.linkedin.com/in/danielvasquezparedes", label: "linkedin.com/in/danielvasquezparedes" },
      goldenfrijoles: { url: "https://goldenfrijoles.com", label: "goldenfrijoles.com" },
      github: { url: "https://github.com/danybgoode", label: "github.com/danybgoode" },
    },
    stats: [
      { figure: "15+", label: "Years in product leadership" },
      { figure: "$70M+", label: "Portfolio owned at AB InBev" },
      { figure: "70+", label: "People led, product & engineering" },
      { figure: "3", label: "Products running in production" },
      { figure: "4", label: "Ventures founded, one acquired" },
      { figure: "MSc", label: "Finance, University of Aberdeen" },
    ],
    snapshot: [
      "I build production software with teams of AI agents, and I design the operating system those teams run on. Three products are live today: an agentic product-management platform, a no-commission marketplace for Mexico, and the open-source plugin framework both are built with.",
      "Before that, fifteen years of product leadership from zero-to-one to Fortune 100 scale — a $70M+ global rewards portfolio and a product and engineering organisation of 70+ people at AB InBev, post-M&A systems integration at Linio through the Falabella acquisition, and four ventures of my own, one of them acquired.",
      "The through-line is turning ambiguity into systems: a delivery cadence humans and agents can both follow, with risk-tiered merge gates, independent cross-model review, and written retrospectives that feed the next session instead of dying in a folder. Agile, rebuilt for a team where most of the contributors are not people.",
    ],
    howIWork: [
      "Plan, build, ship — one user story at a time, with a deterministic gate that has to be green before anything merges.",
      "Risk-tiered review: agents can merge low-risk work on green CI; anything touching money, auth, or database migrations is always a human merge.",
      "Cross-family review on every pull request — the diff gets an independent pass from a different model family before it lands, and every finding is fixed or answered.",
      "Model tiering by task: the stronger model grooms, plans, and reviews; once slices are approved, execution runs on the faster one.",
      "Every epic closes with a retrospective, and durable learnings are promoted into a shared digest that every new session reads first.",
      "Grooming is the front door: a raw ask is reframed onto existing platform primitives before anything new gets built.",
    ],
    experience: {
      featured: [
        {
          company: "Golden Frijoles",
          url: "https://goldenfrijoles.com",
          dates: "2025 — Present",
          title: "Founder & Product Lead · Agentic product-management platform",
          chain: [
            "Built and shipped a commercial multi-tenant SaaS: telemetry ingest and a TypeScript SDK, a TARS adoption funnel, North Star metrics, a typed feature-flag control plane, A/B experiments and signed webhook delivery — one primitive set in place of five stitched-together vendors.",
            "Designed the governance model that lets agents investigate, propose, and act inside bounds: scoped credentials, staged actions, explicit human approval, and an append-only record.",
            "25 epics shipped to production on Next.js, Supabase and Vercel, behind 106 Playwright suites, with tenancy enforced by row-level security and no cross-project read path derived from the request.",
            "Now the flag control plane for the Miyagi Sánchez marketplace — a complete 40-key cutover with policy-bound circuit breakers.",
          ],
          tags: "Product Ops · DevOps · SecOps · FinOps on one set of rails · free tier and paid plans live",
        },
        {
          company: "Miyagi Sánchez",
          url: "https://miyagisanchez.com",
          dates: "2025 — Present",
          title: "Founder & Product Lead · No-commission marketplace for Mexico",
          chain: [
            "Multi-seller marketplace on Medusa v2 and Next.js: anyone can list products, services, rentals, digital goods, subscriptions or events and sell with no commission.",
            "One catalogue reaches buyers four ways: the marketplace, a seller's own domain, an embeddable widget, and AI shopping agents over MCP and UCP endpoints.",
            "147 epics shipped across ten product domains — discovery, checkout and payments, shipping, trust and messaging, agentic commerce, promotions, ticketing — each closed with a written retrospective.",
            "Runs on Cloud Run and Cloud Build behind Cloudflare, with an ad-funded print edition as the first revenue channel.",
          ],
          tags: "Payments · marketplace trust · agent-readable commerce · ~1,000 commits across backend and storefront",
        },
        {
          company: "dobby-foundation",
          url: "https://github.com/danybgoode/dobby-foundation",
          dates: "2025 — Present",
          title: "Creator · Open-source ways-of-work for agent teams",
          chain: [
            "A Claude Code plugin marketplace of ten skills — grooming, doc hygiene, PR review, live smoke tests, standups, weekly recaps, PMO reporting — installed once per project and updated from one place, so an improvement reaches every project without fork drift.",
            "CI guards enforce portability: a leak checker keeps project-specific residue out of every shipped skill, and a contract audit fails the build when a skill declares a dependency nothing provides.",
            "Reproducible, byte-for-byte skill packaging so the same methodology loads into both Claude Code and Cowork.",
          ],
          tags: "The methodology as a product — extracted from a live codebase so a second project could adopt it without forking",
        },
        {
          company: "AB InBev",
          dates: "2020 — 2023",
          title: "Global Principal Product Manager · Largest brewer worldwide",
          chain: [
            "Built the global rewards ecosystem across Central America, Europe and South Korea.",
            "Led a 70+ person cross-functional product and engineering organisation.",
            "Owned a $70M+ portfolio, with campaigns activated at the Super Bowl and The Voice Brasil.",
          ],
        },
        {
          company: "Linio Group",
          dates: "2019 — 2020",
          title: "Group Product Manager · Mexico City",
          chain: [
            "Directed post-M&A systems integration through the Falabella acquisition.",
            "Unified multi-platform infrastructure across the merged organisations.",
          ],
        },
        {
          company: "Bicimensajero.com",
          dates: "2014 — 2016",
          title: "Founder · On-demand bike logistics",
          chain: [
            "Built the full stack solo, in a pre-AI landscape.",
            "Scaled operations to 100+ messengers.",
            "Negotiated the acquisition exit.",
          ],
        },
        {
          company: "CTIN",
          dates: "2012 — 2014",
          title: "Team Lead · Centro de Tecnología e Innovación",
          chain: [
            "Led a Bitcoin remittance platform to 5,000+ active users.",
            "Authored the platform proposal to América Móvil / Grupo Carso.",
          ],
          tags: "Second team: a gamified coding-literacy comic platform for children",
        },
      ],
      earlier: [
        { company: "Wagento Commerce", title: "Head of Customer Experience & Project Management", dates: "2017 — 2019" },
        { company: "MagmaLabs", title: "Senior Product Manager", dates: "2016 — 2017" },
        { company: "Pokapok.mx", title: "Founder — corporate wellness platform", dates: "2016 — 2017" },
        { company: "Nuuch Tech", title: "Founder & Principal Consultant — Magento, CRM, agile coaching", dates: "2012 — 2015" },
        { company: "Grupo Bimbo", title: "FinOps Analyst", dates: "2010 — 2011" },
        { company: "CompuCom · Accenture", title: "Tech Support · Customer Service", dates: "2006 — 2010" },
      ],
    },
    education: [
      { school: "University of Aberdeen · Scotland", credential: "MSc Finance", dates: "2023" },
      { school: "Escuela Bancaria y Comercial · Mexico City", credential: "Bachelor's, International Trade and Business", dates: "" },
    ],
    philosophy: "I build products on purpose.",
    tldr: {
      greeting: "Hi, I'm Daniel Vásquez",
      intro: "Some things about me:",
      bullets: [
        "Learned to code in high school while managing a local computer shop",
        "Started in tech support, moved into software development, then settled in Product Management",
        "Everything I build now runs through agents — grooming, planning, building, review, shipping and reporting",
        "Built <a href=\"https://github.com/danybgoode/dobby-foundation\" target=\"_blank\" rel=\"noopener noreferrer\">dobby-foundation</a>, my open-source operating system for agent product work — ten skills, installed once, reused across every project I build",
        "Run <a href=\"https://goldenfrijoles.com\" target=\"_blank\" rel=\"noopener noreferrer\">goldenfrijoles.com</a>, an agentic product-management platform, and <a href=\"https://miyagisanchez.com\" target=\"_blank\" rel=\"noopener noreferrer\">miyagisanchez.com</a>, a no-commission marketplace for Mexico — both in production",
        "Before all that: $70M+ and 70 people at AB InBev, a post-M&A integration at Linio, and four ventures of my own",
      ],
      punchline: "Have a knack for taking things from 0 to the whole world.",
      contactText: "Find me at:",
      contactEmail: "danielvp1987@gmail.com",
    },
    ui: {
      pageTitle: "Daniel Vásquez — Product & Agentic Delivery",
      pdfTitle: "Daniel Vasquez - CV - Product Engineering and Agentic Delivery",
      metaDesc:
        "Product leader shipping production software with multi-agent teams. Fifteen years from zero-to-one to Fortune 100 scale — AB InBev, Linio, and three products live today.",
      snapshotTitle: "Profile",
      experienceTitle: "Experience",
      earlierTitle: "Earlier Career",
      howIWorkTitle: "How I Work",
      educationTitle: "Education",
      approachTitle: "Approach",
      tldrButton: "TL;DR",
      classicButton: "Classic",
      lastUpdated: "Last updated September 2026",
      viewMarkdown: "View Markdown",
      markdownUrl: "/resume.md",
      downloadPdf: "PDF",
      emailLabel: "Email",
      linkedinLabel: "LinkedIn",
      websiteLabel: "Website",
      githubLabel: "GitHub",
      statsTitle: "At a Glance",
      pdfFooterNote: "Full profile at",
      pdfPrintButton: "Print / Save as PDF",
      pdfBackLink: "← Back to site",
    },
  },

  es: {
    eyebrow: "Liderazgo de Producto · Entrega con Agentes",
    name: "Daniel Vásquez",
    role: "Producto e Ingeniería · Sistemas de Entrega con Agentes",
    disciplines:
      "Quince años de liderazgo de producto, desde cero-a-uno hasta escala Fortune 100 — hoy construyendo software en producción con equipos de agentes, y el sistema operativo sobre el que trabajan.",
    email: "danielvp1987@gmail.com",
    location: "Ciudad de México · Aberdeen, UK",
    links: {
      website: { url: "https://miyagisanchez.com", label: "miyagisanchez.com" },
      linkedin: { url: "https://www.linkedin.com/in/danielvasquezparedes", label: "linkedin.com/in/danielvasquezparedes" },
      goldenfrijoles: { url: "https://goldenfrijoles.com", label: "goldenfrijoles.com" },
      github: { url: "https://github.com/danybgoode", label: "github.com/danybgoode" },
    },
    stats: [
      { figure: "15+", label: "Años en liderazgo de producto" },
      { figure: "$70M+", label: "Portafolio gestionado en AB InBev" },
      { figure: "70+", label: "Personas lideradas, producto e ingeniería" },
      { figure: "3", label: "Productos corriendo en producción" },
      { figure: "4", label: "Emprendimientos fundados, uno adquirido" },
      { figure: "MSc", label: "Finanzas, University of Aberdeen" },
    ],
    snapshot: [
      "Construyo software en producción con equipos de agentes de IA, y diseño el sistema operativo sobre el que esos equipos trabajan. Hoy hay tres productos vivos: una plataforma de product management con agentes, un marketplace sin comisiones para México, y el framework de plugins open source con el que ambos están construidos.",
      "Antes de eso, quince años de liderazgo de producto desde cero-a-uno hasta escala Fortune 100 — un portafolio global de recompensas de más de $70M USD y una organización de producto e ingeniería de más de 70 personas en AB InBev, la integración de sistemas post-M&A en Linio durante la adquisición por Falabella, y cuatro emprendimientos propios, uno de ellos adquirido.",
      "El hilo conductor es convertir la ambigüedad en sistemas: una cadencia de entrega que humanos y agentes pueden seguir por igual, con gates de merge escalonados por riesgo, revisión independiente entre familias de modelos, y retrospectivas escritas que alimentan la siguiente sesión en lugar de morir en una carpeta. Agile, reconstruido para un equipo donde la mayoría de quienes contribuyen no son personas.",
    ],
    howIWork: [
      "Planear, construir, entregar — una historia de usuario a la vez, con un gate determinista que debe estar en verde antes de cualquier merge.",
      "Revisión escalonada por riesgo: los agentes pueden mergear trabajo de bajo riesgo con CI en verde; todo lo que toca dinero, autenticación o migraciones de base de datos siempre lo mergea una persona.",
      "Revisión cruzada en cada pull request — el diff recibe un paso independiente de otra familia de modelos antes de aterrizar, y cada hallazgo se corrige o se responde.",
      "Modelos por tarea: el modelo más fuerte hace grooming, planea y revisa; una vez aprobadas las rebanadas, la ejecución corre en el más rápido.",
      "Cada épica cierra con una retrospectiva, y los aprendizajes duraderos se promueven a un digest compartido que toda sesión nueva lee primero.",
      "El grooming es la puerta de entrada: una petición cruda se reencuadra sobre las primitivas de plataforma que ya existen antes de construir algo nuevo.",
    ],
    experience: {
      featured: [
        {
          company: "Golden Frijoles",
          url: "https://goldenfrijoles.com",
          dates: "2025 — Presente",
          title: "Fundador y Líder de Producto · Plataforma de product management con agentes",
          chain: [
            "Construí y lancé un SaaS comercial multi-tenant: ingesta de telemetría y un SDK de TypeScript, un embudo de adopción TARS, métricas North Star, un plano de control tipado de feature flags, experimentos A/B y entrega firmada por webhook — un solo conjunto de primitivas en lugar de cinco proveedores cosidos entre sí.",
            "Diseñé el modelo de gobernanza que permite a los agentes investigar, proponer y actuar dentro de límites: credenciales acotadas, acciones en etapas, aprobación humana explícita y un registro append-only.",
            "25 épicas entregadas a producción sobre Next.js, Supabase y Vercel, detrás de 106 suites de Playwright, con tenencia forzada por row-level security y sin ninguna ruta de lectura entre proyectos derivada del request.",
            "Hoy es el plano de control de flags del marketplace Miyagi Sánchez — una migración completa de 40 claves con circuit breakers acotados por política.",
          ],
          tags: "Product Ops · DevOps · SecOps · FinOps sobre un solo set de rieles · plan gratuito y planes de pago en vivo",
        },
        {
          company: "Miyagi Sánchez",
          url: "https://miyagisanchez.com",
          dates: "2025 — Presente",
          title: "Fundador y Líder de Producto · Marketplace sin comisiones para México",
          chain: [
            "Marketplace multi-vendedor sobre Medusa v2 y Next.js donde cualquiera puede listar productos, servicios, rentas, bienes digitales, suscripciones o eventos y vender sin comisión.",
            "Los vendedores llegan a compradores por cuatro vías desde un solo catálogo: el marketplace, su propio dominio, un widget embebible y agentes de compra de IA vía endpoints MCP y UCP.",
            "147 épicas entregadas en diez dominios de producto — descubrimiento, checkout y pagos, envíos, confianza y mensajería, comercio agéntico, promociones, boletaje — cada una cerrada con una retrospectiva escrita.",
            "Corre sobre Cloud Run y Cloud Build detrás de Cloudflare, con una edición impresa financiada por publicidad como primer canal de ingresos.",
          ],
          tags: "Pagos · confianza en marketplace · comercio legible por agentes · ~1,000 commits entre backend y storefront",
        },
        {
          company: "dobby-foundation",
          url: "https://github.com/danybgoode/dobby-foundation",
          dates: "2025 — Presente",
          title: "Creador · Formas de trabajo open source para equipos de agentes",
          chain: [
            "Un marketplace de plugins para Claude Code con diez skills — grooming, higiene documental, revisión de PRs, smoke tests en vivo, standups, recaps semanales, reporteo tipo PMO — instalados una vez por proyecto y actualizados desde un solo lugar, para que una mejora llegue a todos los proyectos sin fork drift.",
            "Guardas de CI aseguran la portabilidad: un verificador de fugas mantiene fuera de cada skill el residuo específico del proyecto, y una auditoría del contrato skill-script rompe el build cuando un skill declara una dependencia que nada provee.",
            "Empaquetado de skills reproducible, byte a byte, para que la misma metodología cargue tanto en Claude Code como en Cowork.",
          ],
          tags: "La metodología como producto — extraída de un código vivo para que un segundo proyecto pudiera adoptarla sin bifurcarla",
        },
        {
          company: "AB InBev",
          dates: "2020 — 2023",
          title: "Global Principal Product Manager · La cervecera más grande del mundo",
          chain: [
            "Construí el ecosistema global de recompensas en Centroamérica, Europa y Corea del Sur.",
            "Lideré una organización multidisciplinaria de más de 70 personas de producto e ingeniería.",
            "Gestioné un portafolio de más de $70M USD, con campañas activadas en el Super Bowl y The Voice Brasil.",
          ],
        },
        {
          company: "Linio Group",
          dates: "2019 — 2020",
          title: "Group Product Manager · Ciudad de México",
          chain: [
            "Dirigí la integración de sistemas post-M&A durante la adquisición por Falabella.",
            "Unifiqué la infraestructura multiplataforma de las organizaciones fusionadas.",
          ],
        },
        {
          company: "Bicimensajero.com",
          dates: "2014 — 2016",
          title: "Fundador · Logística en bicicleta bajo demanda",
          chain: [
            "Desarrollé el stack completo yo solo, en una era pre-IA.",
            "Escalé la operación a más de 100 mensajeros.",
            "Negocié la salida por adquisición.",
          ],
        },
        {
          company: "CTIN",
          dates: "2012 — 2014",
          title: "Líder de Equipo · Centro de Tecnología e Innovación",
          chain: [
            "Llevé una plataforma de remesas con Bitcoin a más de 5,000 usuarios activos.",
            "Escribí la propuesta de plataforma para América Móvil / Grupo Carso.",
          ],
          tags: "Segundo equipo: un cómic interactivo y gamificado para enseñar programación a niños",
        },
      ],
      earlier: [
        { company: "Wagento Commerce", title: "Director de Experiencia de Cliente y Gestión de Proyectos", dates: "2017 — 2019" },
        { company: "MagmaLabs", title: "Senior Product Manager", dates: "2016 — 2017" },
        { company: "Pokapok.mx", title: "Fundador — plataforma de bienestar corporativo", dates: "2016 — 2017" },
        { company: "Nuuch Tech", title: "Fundador y Consultor Principal — Magento, CRM, coaching ágil", dates: "2012 — 2015" },
        { company: "Blue Label Telecoms", title: "Analista de Negocio", dates: "2010 — 2011" },
        { company: "CompuCom · Accenture", title: "Soporte Técnico y Servicio al Cliente", dates: "2006 — 2010" },
      ],
    },
    education: [
      { school: "University of Aberdeen · Escocia", credential: "MSc en Finanzas", dates: "2023" },
      { school: "Escuela Bancaria y Comercial · Ciudad de México", credential: "Licenciatura en Comercio y Negocios Internacionales", dates: "" },
    ],
    philosophy: "Construyo productos con propósito.",
    tldr: {
      greeting: "Hola, soy Daniel Vásquez",
      intro: "Algunas cosas sobre mí:",
      bullets: [
        "Aprendí a programar en la prepa mientras administraba una tienda local de computación",
        "Empecé en soporte técnico, pasé a desarrollo de software y después me consolidé en Product Management",
        "Todo lo que construyo ahora pasa por agentes — grooming, planeación, construcción, revisión, entrega y reporteo",
        "Construí <a href=\"https://github.com/danybgoode/dobby-foundation\" target=\"_blank\" rel=\"noopener noreferrer\">dobby-foundation</a>, mi sistema operativo open source para trabajo de producto con agentes — diez skills, instalados una vez, reutilizados en cada proyecto que construyo",
        "Opero <a href=\"https://goldenfrijoles.com\" target=\"_blank\" rel=\"noopener noreferrer\">goldenfrijoles.com</a>, una plataforma de product management con agentes, y <a href=\"https://miyagisanchez.com\" target=\"_blank\" rel=\"noopener noreferrer\">miyagisanchez.com</a>, un marketplace sin comisiones para México — ambos en producción",
        "Antes de todo eso: $70M+ y 70 personas en AB InBev, una integración post-M&A en Linio, y cuatro emprendimientos propios",
      ],
      punchline: "Tengo facilidad para llevar las cosas de 0 a todo el mundo.",
      contactText: "Encuéntrame en:",
      contactEmail: "danielvp1987@gmail.com",
    },
    ui: {
      pageTitle: "Daniel Vásquez — Producto y Entrega con Agentes",
      pdfTitle: "Daniel Vasquez - CV - Producto e Ingenieria con Agentes",
      metaDesc:
        "Líder de producto que entrega software en producción con equipos de agentes. Quince años desde cero-a-uno hasta escala Fortune 100 — AB InBev, Linio, y tres productos vivos hoy.",
      snapshotTitle: "Perfil",
      experienceTitle: "Experiencia",
      earlierTitle: "Trayectoria Previa",
      howIWorkTitle: "Cómo Trabajo",
      educationTitle: "Formación",
      approachTitle: "Enfoque",
      tldrButton: "TL;DR",
      classicButton: "Clásico",
      lastUpdated: "Última actualización: Septiembre 2026",
      viewMarkdown: "Ver Markdown",
      markdownUrl: "/resume-es.md",
      downloadPdf: "PDF",
      emailLabel: "Correo",
      linkedinLabel: "LinkedIn",
      websiteLabel: "Sitio Web",
      githubLabel: "GitHub",
      statsTitle: "En Cifras",
      pdfFooterNote: "Perfil completo en",
      pdfPrintButton: "Imprimir / Guardar como PDF",
      pdfBackLink: "← Volver al sitio",
    },
  },
};

// Default export has both en and es, and aliases top-level to en for backward-compatibility in templates
export default {
  ...resumeData.en,
  en: resumeData.en,
  es: resumeData.es,
};
